// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbYRccMwpEQtyg1dH6_LABXrmi9A2btk',
    appId: '1:750928338418:web:f3bfefc692dad66db25f6b',
    messagingSenderId: '750928338418',
    projectId: 'new-appmy',
    authDomain: 'new-appmy.firebaseapp.com',
    storageBucket: 'new-appmy.appspot.com',
    measurementId: 'G-SWZ5N5YSXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFldlmvxsAVpZYqWZ_Mx2w4zJxAKAmtlw',
    appId: '1:750928338418:android:eee98f07e509e1c3b25f6b',
    messagingSenderId: '750928338418',
    projectId: 'new-appmy',
    storageBucket: 'new-appmy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2l-pnVH0MF0mgJUZw70UlC2_2x9cZIM',
    appId: '1:750928338418:ios:510212268bdd6a0eb25f6b',
    messagingSenderId: '750928338418',
    projectId: 'new-appmy',
    storageBucket: 'new-appmy.appspot.com',
    iosClientId: '750928338418-ktc8p7takr9de6nks8oa0lc1nktqu79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.resturantProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2l-pnVH0MF0mgJUZw70UlC2_2x9cZIM',
    appId: '1:750928338418:ios:510212268bdd6a0eb25f6b',
    messagingSenderId: '750928338418',
    projectId: 'new-appmy',
    storageBucket: 'new-appmy.appspot.com',
    iosClientId: '750928338418-ktc8p7takr9de6nks8oa0lc1nktqu79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.resturantProject',
  );
}
